testchanges

diff --git a/.github/workflows/publish-to-ecr.yaml b/.github/workflows/publish-to-ecr.yaml
--- a/.github/workflows/publish-to-ecr.yaml
+++ b/.github/workflows/publish-to-ecr.yaml
@@ -49,7 +49,12 @@ jobs:
 
       - name: Run Wiz CLI image scan
         id: scan
-        run: ./wizcli docker scan -i $REGISTRY/$REPOSITORY:${COMMIT_SHA} --policy ${ODLUSER}-vuln-block
+        run: |
+    if [ -z "${ODLUSER}" ]; then
+      echo "Error: ODLUSER environment variable is not set."
+      exit 1
+    fi
+    ./wizcli docker scan -i $REGISTRY/$REPOSITORY:${COMMIT_SHA} --policy ${ODLUSER}-vuln-block
         continue-on-error: false
         env:
           REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
@@ -110,4 +115,3 @@ jobs:
         run: |
           IMAGE_URI=$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$REPOSITORY:$COMMIT_SHA
           ./wizcli docker tag -i $IMAGE_URI
-          
